credentials:
  usernames:
    jsmith: # To be replaced with you real username
      email: jsmith@gmail.com
      name: John Smith
      password: '123' # To be replaced with hashed password
cookie:
  expiry_days: 30
  key: some_signature_key # replace
  name: Gartenbewässerung-Auth
preauthorized:
  emails:
  - melsby@gmail.com